# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EoRNyfabBQ71_8fWD2Dye9Wg0rT--iV
"""

import socket

def ip_to_domain(ip_address):
    try:
        domain_name = socket.gethostbyaddr(ip_address)
        return domain_name[0]
    except socket.herror:
        return "Unable to resolve IP to domain."

def domain_to_ip(domain_name):
    try:
        ip_address = socket.gethostbyname(domain_name)
        return ip_address
    except socket.gaierror:
        return "Unable to resolve domain to IP."

def main():
    while True:
        print("DNS Lookup Menu:")
        print("1. IP to Domain")
        print("2. Domain to IP")
        print("3. Exit")
        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            ip_address = input("Enter the IP address: ")
            domain = ip_to_domain(ip_address)
            print(f"Domain: {domain}")
        elif choice == '2':
            domain_name = input("Enter the domain name: ")
            ip = domain_to_ip(domain_name)
            print(f"IP Address: {ip}")
        elif choice == '3':
            print("Exiting the program.")
            break
        else:
            print("Invalid choice. Please select 1, 2, or 3.")

if __name__ == "__main__":
    main()

